### ISSUE TITLE
Installing pyml package (Diskuv distribution)

### ISSUE THREAD

**Issue by Noteeeeeee** [thierry-martinez/pyml#88]
I tried to install pyml with opam but it didn't work.

Here is the link to the discussion on ocaml forum https://discuss.ocaml.org/t/installing-pyml-package/10751/4 

@jonahbeckford maintains the Diskuv distribution

**Comment by thierry-martinez** [comment]
Thank you for reporting! This error should not happen with `stdcompat.19` and above, since `dune` is now used as default build system. You may try:
```
opam pin add https://github.com/thierry-martinez/stdcompat.git
```

Moreover, thanks to your report, the `Makefile`-based build system has been fixed in 66c70ec to install the `.lib` files on Windows (but the `Makefile`-based build system is not used anymore, except for coccinelle bundles as far as I know).

**Comment by jonahbeckford** [comment]
I have opened https://github.com/diskuv/dkml-installer-ocaml/issues/12 to track bumping up the versions for at least `stdcompat` in the DKML distribution. Thanks!!

I think this issue can be closed.

**Comment by thierry-martinez** [comment]
Thanks, @jonahbeckford !
